root@Sergey-PC:~#
root@Sergey-PC:~# apt install mc
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libssh2-1 mc-data unzip
Suggested packages:
  arj catdvi | texlive-binaries dbview djvulibre-bin genisoimage gv imagemagick links | w3m | lynx odt2txt
  poppler-utils python python-boto python-tz xpdf | pdf-viewer zip
The following NEW packages will be installed:
  libssh2-1 mc mc-data unzip
0 upgraded, 4 newly installed, 0 to remove and 8 not upgraded.
Need to get 1,896 kB of archives.
After this operation, 7,804 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 libssh2-1 amd64 1.5.0-2ubuntu0.1 [70.2 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/universe amd64 mc-data all 3:4.8.15-2 [1,202 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial/universe amd64 mc amd64 3:4.8.15-2 [462 kB]
68% [3 mc 90.7 kB/462 kB 20%]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 unzip amd64 6.0-20ubuntu1.1 [162 kB]
Fetched 1,896 kB in 1min 52s (16.8 kB/s)
Selecting previously unselected package libssh2-1:amd64.
(Reading database ... 32167 files and directories currently installed.)
Preparing to unpack .../libssh2-1_1.5.0-2ubuntu0.1_amd64.deb ...
Unpacking libssh2-1:amd64 (1.5.0-2ubuntu0.1) ...
Selecting previously unselected package mc-data.
Preparing to unpack .../mc-data_3%3a4.8.15-2_all.deb ...
Unpacking mc-data (3:4.8.15-2) ...
Selecting previously unselected package mc.
Preparing to unpack .../mc_3%3a4.8.15-2_amd64.deb ...
Unpacking mc (3:4.8.15-2) ...
Selecting previously unselected package unzip.
Preparing to unpack .../unzip_6.0-20ubuntu1.1_amd64.deb ...
Unpacking unzip (6.0-20ubuntu1.1) ...
Processing triggers for libc-bin (2.23-0ubuntu11.3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up libssh2-1:amd64 (1.5.0-2ubuntu0.1) ...
Setting up mc-data (3:4.8.15-2) ...
Setting up mc (3:4.8.15-2) ...
Setting up unzip (6.0-20ubuntu1.1) ...
Processing triggers for libc-bin (2.23-0ubuntu11.3) ...
root@Sergey-PC:~#
root@Sergey-PC:~#
root@Sergey-PC:~#    
